POST http://localhost:4000
Content-Type: application/json

{
    "query" : "query { status { health mode version } }"
}

###
POST https://library-31bw.onrender.com
Content-Type: application/json

{
    "query" : "query { books { title reserved author reservedDate reservedBy { id } reservationHistory available expired { isExpired } } }"
}

###
POST https://library-31bw.onrender.com
Content-Type: application/json

{
    "query" : "query { status { health mode version } }"
}

###
POST http://localhost:4000
Content-Type: application/json

{
    "query" : 'mutation { login(username: "mdridrrrrrrrrr", password: "asdfgh123@") { value id } }'
}